[mypy]
python_version = 3.13
mypy_path = src
disallow_untyped_defs = True
check_untyped_defs = True
warn_return_any = True
show_error_codes = True
warn_unused_ignores = False

[mypy-sonartk.sound.openal_lite.*]
ignore_errors = True

[mypy-pyglet.*]
ignore_missing_imports = True

[mypy-pyperclip.*]
ignore_missing_imports = True

[mypy-accessible_output2.*]
ignore_missing_imports = True

[mypy-test.ui.element.test_text_box]
ignore_errors = True

[mypy-test.ui.element.*]
ignore_errors = True
[mypy-pyogg.*]
ignore_missing_imports = True

[mypy-ijson.*]
ignore_missing_imports = True

[mypy-pytest]
ignore_missing_imports = True

[mypy-pytest_mock]
ignore_missing_imports = True
