[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sonartk"
authors = [
    {name = "Timothy Breitenfeldt", email = "timothyjb310@gmail.com"},
]
readme = "readme.md"
version = "0.1.2"
description = "A library used to create audio games built on top of Pyglet."
requires-python = ">=3.13"
keywords = ["development", "accessibility", "screen reader", "sonartk", "sonar tk"]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "accessible_output2",
    "pyglet",
    "pyperclip",
    "ijson",
    "pyogg",
]

[project.optional-dependencies]
test = [
    "build",
    "pytest",
    "pytest-mock",
    "pytest-cov",
]
dev = [
    "mypy",
    "flake8",
    "black",
    "pre-commit",
]
docs = [
    "mkdocs==1.6.1",
    "mkdocs-material==9.5.47",
    "mkdocstrings==1.0.4",
    "mkdocstrings-python==2.0.3",
]

[project.urls]
repository = "https://github.com/tbreitenfeldt/sonar-tk"
bugtracker = "https://github.com/tbreitenfeldt/sonar-tk/issues"

[tool.black]
target-version = ['py313']
line-length = 79
include = "\\.pyi?$"
exclude = """
/(
    /.git
  | /.hg
  | /.mypy_cache
  | /.tox
  | /.venv
  | _build
  | buck-out
  | build
  | dist
)/
"""

[tool.flake8]
max-line-length = 79
max-complexity = 18
select = "B,C,E,F,W,T4,B9"
ignore = "E203,E266,E501,E704,E711,E712,E722,W503,F403,F405,F811"
exclude = [".git", "examples", "test", ".venv", "src/sonartk/sound/openal_lite"]

