[pytest]
addopts = --cov=src/sonartk --cov-report html --no-cov-on-fail --cov-branch --cov-fail-under=90
minversion = 6.0
norecursedirs = examples dist src/sonartk/sound/openal_lite
testpaths = test
filterwarnings =
    default:::sonartk.*
